### ISSUE TITLE
Update/redesign Github Pages titles/header section (challenges, principles)

### ISSUE THREAD

**Issue by danhon** [CA-CODE-Works/Vision-2023#31]
Currently duplicates h1 and includes duplicate site description on all pages.

**Comment by timothyshambra** [comment]
Looking into this further, the page title is generated from the heading, which then is also populated into the top section. I could potentially create unique page styles with their own unique top sections, but it would start getting messy quickly. 

What if we leave the heading in the main section, and have "Vision 2023" in the top section? It would solve duplicated headings and we won't have to manage additional page styles.

In addition, the readability starts getting funky in the mobile view. If we were to implement the proposed change.

![Screen Shot 2021-01-15 at 12 14 16 PM](https://user-images.githubusercontent.com/20093966/104774345-5e2ab700-572b-11eb-9e06-3bd12e9d8719.png)

**Comment by timothyshambra** [comment]
Spoke with @danhon on teams and came to a solution. Due to the way the template is built, we are going to have standard text in the top section.

Vision 2023
California's Statewide Strategic Plan to use technology to meet our society’s goals, and make progress on the big, complex problems affecting us all.
